id: backend_connecting
owner: device
conditions:
  match: all
  items:
    - flag: backend_connecting
sidebars: false
buttons: {preset: none}
items:
  - item: header_clock
  - item: error_message
  - item: system_message
    animations: []
