id: idle
owner: device
conditions:
  match: all
  items:
    - flag: idle_ready
sidebars: true
buttons: {preset: standard}
items:
  - item: big_clock
    x: 512
    y: 300
  - item: big_date
    x: 512
    y: 50
