id: listening
owner: device
conditions:
  match: all
  items:
    - flag: listening
sidebars: true
buttons: {preset: standard}
items:
  - item: header_clock
  - item: activity_listening
    x: 512
    y: 295
    animations:
      - preset: activity_slide_up
        when: {flag: listening}
      - preset: mic_input_pulse
        when: {flag: listening}
