id: replying
conditions:
  match: all
  items:
    - flag: replying
sidebars: true
buttons: {preset: standard}
items:
  - item: header_clock
  - item: activity_replay
    x: 422
    y: 205
    animations:
      - preset: activity_slide_right
        when: {flag: replying}
      - preset: soft_pulse
        when: {flag: replying}
