id: thinking
conditions:
  match: all
  items:
    - flag: thinking
sidebars: true
buttons: {preset: standard}
items:
  - item: header_clock
  - item: activity_thinking
    x: 422
    y: 205
    animations:
      - preset: activity_slide_up
        when: {flag: thinking}
      - preset: thinking_dots
        when: {flag: thinking}
