id: timer_finished
owner: backend
conditions:
  match: all
  items:
    - flag: timer_finished
sidebars: true
buttons: {preset: standard}
items:
  - item: header_clock
  - item: activity_timer
    x: 180
    y: 195
    animations:
      - preset: activity_slide_up
        when: {flag: timer_finished}
      - preset: timer_dot
        when: {flag: timer_finished}
