id: updating
owner: device
conditions:
  match: any
  items:
    - flag: ota_active
    - flag: updating
sidebars: false
buttons: {preset: none}
items:
  - item: header_clock
  - item: ota_progress
    x: 512
    y: 529
  - item: updating_text
