id: weather_test
owner: backend
sidebars: true
buttons: {preset: standard}
items:
  - item: header_clock
  - item: weather_test_top_left_cross
  - item: weather_test_top_left_label
  - item: weather_test_top_right_cross
  - item: weather_test_top_right_label
  - item: weather_test_bottom_left_cross
  - item: weather_test_bottom_left_label
  - item: weather_test_bottom_right_cross
  - item: weather_test_bottom_right_label
  - item: weather_test_center_cross
  - item: weather_test_center_label
