#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import re


def parse_scalar(value: str):
    value = value.strip()
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value.strip("\"'")


def parse_simple_yaml(path: Path) -> dict[str, dict[str, object]]:
    data: dict[str, dict[str, object]] = {}
    current_section: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if not line.startswith(" ") and line.endswith(":"):
            current_section = line[:-1].strip()
            data[current_section] = {}
            continue
        if current_section is None or ":" not in line:
            continue
        key, value = line.strip().split(":", 1)
        data[current_section][key.strip()] = parse_scalar(value)
    return data


def load_yaml(path: Path) -> dict[str, dict[str, object]]:
    try:
        import yaml

        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        return payload or {}
    except ModuleNotFoundError:
        return parse_simple_yaml(path)


def required(data: dict[str, dict[str, object]], section: str, key: str):
    try:
        value = data[section][key]
    except KeyError as exc:
        raise SystemExit(f"Missing firmware endpoint config value: {section}.{key}") from exc
    if value == "":
        raise SystemExit(f"Empty firmware endpoint config value: {section}.{key}")
    return value


def optional(data: dict[str, dict[str, object]], section: str, key: str, default):
    return data.get(section, {}).get(key, default)


def bool_literal(value: object) -> str:
    return "true" if bool(value) else "false"


def string_literal(value: object) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_header(data: dict[str, dict[str, object]]) -> str:
    endpoint_id = required(data, "endpoint", "id")
    firmware_version = required(data, "endpoint", "firmware_version")
    host = required(data, "node", "host")
    http_port = required(data, "node", "http_port")
    ws_port = required(data, "node", "ws_port")
    heartbeat_path = required(data, "node", "heartbeat_path")
    voice_ws_path = required(data, "node", "voice_ws_path")
    use_tls = required(data, "node", "use_tls")
    encoding = required(data, "audio", "encoding")
    sample_rate_hz = required(data, "audio", "sample_rate_hz")
    channels = required(data, "audio", "channels")
    chunk_samples = required(data, "audio", "chunk_samples")
    heartbeat_interval_ms = required(data, "behavior", "heartbeat_interval_ms")
    reconnect_backoff_ms = required(data, "behavior", "reconnect_backoff_ms")
    discovery_enabled = required(data, "behavior", "discovery_enabled")
    log_stream_enabled = optional(data, "debug_log", "enabled", False)
    log_stream_host = optional(data, "debug_log", "host", host)
    log_stream_port = optional(data, "debug_log", "udp_port", 9010)

    return f"""#pragma once

// Generated from firmware/config/endpoint.yaml or endpoint.example.yaml.
// Do not edit this file by hand.

namespace hexe::config {{

constexpr const char *kEndpointId = {string_literal(endpoint_id)};
constexpr const char *kEndpointFirmwareVersion = {string_literal(firmware_version)};
constexpr const char *kEndpointBackendHost = {string_literal(host)};
constexpr int kEndpointHttpPort = {int(http_port)};
constexpr int kEndpointWsPort = {int(ws_port)};
constexpr const char *kEndpointHeartbeatPath = {string_literal(heartbeat_path)};
constexpr const char *kEndpointVoiceWsPath = {string_literal(voice_ws_path)};
constexpr bool kEndpointUseTls = {bool_literal(use_tls)};
constexpr const char *kEndpointAudioEncoding = {string_literal(encoding)};
constexpr int kEndpointAudioSampleRateHz = {int(sample_rate_hz)};
constexpr int kEndpointAudioChannels = {int(channels)};
constexpr int kEndpointAudioChunkSamples = {int(chunk_samples)};
constexpr int kEndpointHeartbeatIntervalMs = {int(heartbeat_interval_ms)};
constexpr int kEndpointReconnectBackoffMs = {int(reconnect_backoff_ms)};
constexpr bool kEndpointDiscoveryEnabled = {bool_literal(discovery_enabled)};
constexpr bool kEndpointLogStreamEnabled = {bool_literal(log_stream_enabled)};
constexpr const char *kEndpointLogStreamHost = {string_literal(log_stream_host)};
constexpr int kEndpointLogStreamUdpPort = {int(log_stream_port)};

}}  // namespace hexe::config
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    data = load_yaml(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_header(data), encoding="utf-8")


if __name__ == "__main__":
    main()
