#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

from validate_board_profiles import ValidationError, load_profile, validate_profile


def cmake_quote(value: object) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def cmake_bool(value: object) -> str:
    return "TRUE" if bool(value) else "FALSE"


def int_literal(value: object) -> int:
    if value is None:
        return -1
    return int(value)


def pascal_name(value: object) -> str:
    text = str(value)
    parts = re.split(r"[^A-Za-z0-9]+", text)
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


def add_const(lines: list[str], name: str, value: object) -> None:
    lines.append(f"constexpr int {name} = {int_literal(value)};")


def render_cmake(profile: dict[str, object], profile_path: Path) -> str:
    board_profile = str(profile["board_profile"])
    display_name = str(profile["display_name"])
    support_status = str(profile["support_status"])
    build = profile["build"]
    hardware = profile["hardware"]
    adapters = profile["adapters"]
    if not isinstance(build, dict) or not isinstance(hardware, dict) or not isinstance(adapters, dict):
        raise ValidationError("validated profile lost required object sections")

    definitions = build.get("compile_definitions")
    source_files = adapters.get("source_files")
    if not isinstance(definitions, list) or not all(isinstance(item, str) for item in definitions):
        raise ValidationError(f"{board_profile}: build.compile_definitions must be a string list")
    if not isinstance(source_files, list) or not all(isinstance(item, str) for item in source_files):
        raise ValidationError(f"{board_profile}: adapters.source_files must be a string list")

    lines = [
        "# Generated from firmware/boards/*/board.yaml.",
        "# Do not edit by hand.",
        f"set(HEXE_BOARD_PROFILE {cmake_quote(board_profile)})",
        f"set(HEXE_BOARD_PROFILE_PATH {cmake_quote(profile_path)})",
        f"set(HEXE_BOARD_DISPLAY_NAME {cmake_quote(display_name)})",
        f"set(HEXE_BOARD_SUPPORT_STATUS {cmake_quote(support_status)})",
        f"set(HEXE_BOARD_IDF_TARGET {cmake_quote(build.get('idf_target'))})",
        f"set(HEXE_BOARD_PARTITION_SCHEMA {cmake_quote(build.get('partition_schema'))})",
        f"set(HEXE_BOARD_APP_SLOT_SIZE {cmake_quote(build.get('app_slot_size'))})",
        f"set(HEXE_BOARD_SOC {cmake_quote(hardware.get('soc'))})",
        f"set(HEXE_BOARD_FLASH_SIZE {cmake_quote(hardware.get('flash_size'))})",
        f"set(HEXE_BOARD_PSRAM_SIZE {cmake_quote(hardware.get('psram_size'))})",
        f"set(HEXE_BOARD_RECOVERY_APP {cmake_bool(build.get('recovery_app'))})",
        f"set(HEXE_BOARD_ADAPTER_BUILDABLE {cmake_bool(adapters.get('buildable'))})",
        "set(HEXE_BOARD_DEFINITIONS",
    ]
    for definition in definitions:
        lines.append(f"  {definition}")
    lines.extend(
        [
            ")",
            "set(HEXE_BOARD_SRCS",
        ]
    )
    for source in source_files:
        lines.append(f"  {cmake_quote(source)}")
    lines.extend(
        [
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def render_pin_header(profile: dict[str, object], profile_path: Path) -> str:
    board_profile = str(profile["board_profile"])
    build = profile["build"]
    hardware = profile["hardware"]
    wiring = profile["wiring"]
    if not isinstance(build, dict) or not isinstance(hardware, dict) or not isinstance(wiring, dict):
        raise ValidationError("validated profile lost wiring section")
    wireless = hardware.get("wireless")
    if not isinstance(wireless, dict):
        raise ValidationError("validated profile lost wireless section")
    ble_transport = str(wireless.get("transport") or "unknown")
    ble_supported = bool(wireless.get("bluetooth")) and ble_transport == "native" and build.get("idf_target") == "esp32s3"
    ble_status = "active" if ble_supported and profile.get("support_status") == "active" else "planned"
    if not ble_supported:
        ble_status = "coprocessor_pending" if wireless.get("coprocessor") else "unsupported"

    lines = [
        "#pragma once",
        "",
        "// Generated from firmware/boards/*/board.yaml.",
        "// Do not edit this file by hand.",
        "",
        "namespace hexe::board::pins {",
        "",
        f'constexpr const char *kBoardProfile = "{board_profile}";',
        f'constexpr const char *kBoardProfilePath = "{profile_path}";',
        f'constexpr const char *kSoc = "{hardware.get("soc")}";',
        f'constexpr const char *kIdfTarget = "{build.get("idf_target")}";',
        f'constexpr const char *kPartitionSchema = "{build.get("partition_schema")}";',
        f'constexpr const char *kAppSlotSize = "{build.get("app_slot_size")}";',
        f'constexpr const char *kFlashSize = "{hardware.get("flash_size")}";',
        f'constexpr const char *kPsramSize = "{hardware.get("psram_size")}";',
        f"constexpr bool kBleOnboardingSupported = {'true' if ble_supported else 'false'};",
        f'constexpr const char *kBleOnboardingTransport = "{ble_transport}";',
        f'constexpr const char *kBleOnboardingStatus = "{ble_status}";',
        "constexpr int kNoPin = -1;",
        "",
    ]

    gpios = wiring.get("gpios", [])
    i2c_buses = wiring.get("i2c_buses", [])
    i2s_buses = wiring.get("i2s_buses", [])
    spi_buses = wiring.get("spi_buses", [])
    led_strips = wiring.get("led_strips", [])

    if isinstance(gpios, list):
        for entry in gpios:
            if not isinstance(entry, dict):
                continue
            prefix = f"k{pascal_name(entry.get('name'))}"
            add_const(lines, prefix, entry.get("gpio"))
            lines.append(f"constexpr bool {prefix}ActiveLow = {'true' if bool(entry.get('active_low')) else 'false'};")
        if gpios:
            lines.append("")

    if isinstance(i2c_buses, list):
        for entry in i2c_buses:
            if not isinstance(entry, dict):
                continue
            prefix = f"k{pascal_name(entry.get('name'))}"
            add_const(lines, f"{prefix}Port", entry.get("port"))
            add_const(lines, f"{prefix}Sda", entry.get("sda"))
            add_const(lines, f"{prefix}Scl", entry.get("scl"))
            add_const(lines, f"{prefix}ClockHz", entry.get("clock_hz"))
            devices = entry.get("devices", [])
            if isinstance(devices, list):
                for device in devices:
                    if isinstance(device, dict):
                        add_const(lines, f"{prefix}{pascal_name(device.get('name'))}Address", device.get("address"))
        if i2c_buses:
            lines.append("")

    if isinstance(i2s_buses, list):
        for entry in i2s_buses:
            if not isinstance(entry, dict):
                continue
            prefix = f"k{pascal_name(entry.get('name'))}"
            add_const(lines, f"{prefix}Port", entry.get("port"))
            add_const(lines, f"{prefix}Mclk", entry.get("mclk"))
            add_const(lines, f"{prefix}Bclk", entry.get("bclk"))
            add_const(lines, f"{prefix}Lrclk", entry.get("lrclk"))
            add_const(lines, f"{prefix}Din", entry.get("din"))
            add_const(lines, f"{prefix}Dout", entry.get("dout"))
        if i2s_buses:
            lines.append("")

    if isinstance(spi_buses, list):
        for entry in spi_buses:
            if not isinstance(entry, dict):
                continue
            prefix = f"k{pascal_name(entry.get('name'))}"
            add_const(lines, f"{prefix}Clk", entry.get("clk"))
            add_const(lines, f"{prefix}Mosi", entry.get("mosi"))
            add_const(lines, f"{prefix}Miso", entry.get("miso"))
            add_const(lines, f"{prefix}Cs", entry.get("cs"))
            add_const(lines, f"{prefix}Dc", entry.get("dc"))
            add_const(lines, f"{prefix}Reset", entry.get("reset"))
            add_const(lines, f"{prefix}Backlight", entry.get("backlight"))
            add_const(lines, f"{prefix}Data0", entry.get("data0"))
            add_const(lines, f"{prefix}Data1", entry.get("data1"))
            add_const(lines, f"{prefix}Data2", entry.get("data2"))
            add_const(lines, f"{prefix}Data3", entry.get("data3"))
            add_const(lines, f"{prefix}Te", entry.get("te"))
        if spi_buses:
            lines.append("")

    if isinstance(led_strips, list):
        for entry in led_strips:
            if not isinstance(entry, dict):
                continue
            prefix = f"k{pascal_name(entry.get('name'))}"
            add_const(lines, f"{prefix}Data", entry.get("data"))
            add_const(lines, f"{prefix}Power", entry.get("power"))
            add_const(lines, f"{prefix}PixelCount", entry.get("pixel_count"))
        if led_strips:
            lines.append("")

    aliases: list[tuple[str, str]] = []
    if board_profile == "esp_box_3":
        aliases = [
            ("kI2cScl", "kPrimaryScl"),
            ("kI2cSda", "kPrimarySda"),
            ("kI2sLrclk", "kAudioLrclk"),
            ("kI2sBclk", "kAudioBclk"),
            ("kI2sMclk", "kAudioMclk"),
            ("kI2sMicDin", "kAudioDin"),
            ("kI2sSpeakerDout", "kAudioDout"),
        ]
    elif board_profile == "ha_voice_pe":
        aliases = [
            ("kVoicePeMicBclk", "kMicrophoneBclk"),
            ("kVoicePeMicLrclk", "kMicrophoneLrclk"),
            ("kVoicePeMicDin", "kMicrophoneDin"),
            ("kVoicePeMicPort", "kMicrophonePort"),
            ("kVoicePeVoiceKitReset", "kVoiceKitReset"),
            ("kVoicePeI2cPort", "kAudioControlPort"),
            ("kVoicePeI2cSda", "kAudioControlSda"),
            ("kVoicePeI2cScl", "kAudioControlScl"),
            ("kVoicePeI2cClockHz", "kAudioControlClockHz"),
            ("kVoicePeVoiceKitI2cAddress", "kAudioControlVoiceKitAddress"),
            ("kVoicePeSpeakerCodecI2cAddress", "kAudioControlSpeakerCodecAddress"),
            ("kVoicePeSpeakerLrclk", "kSpeakerLrclk"),
            ("kVoicePeSpeakerBclk", "kSpeakerBclk"),
            ("kVoicePeSpeakerDout", "kSpeakerDout"),
            ("kVoicePeSpeakerPort", "kSpeakerPort"),
            ("kVoicePeSpeakerAmp", "kSpeakerAmp"),
            ("kVoicePeCenterButton", "kCenterButton"),
            ("kVoicePeHardwareMute", "kHardwareMute"),
            ("kVoicePeDialA", "kDialA"),
            ("kVoicePeDialB", "kDialB"),
            ("kVoicePeLedData", "kLedRingData"),
            ("kVoicePeLedPower", "kLedRingPower"),
            ("kVoicePeLedCount", "kLedRingPixelCount"),
        ]
    elif board_profile == "waveshare_s3_touch_lcd_1_85c_box_v2":
        aliases = [
            ("kWs185I2cPort", "kPeripheralControlPort"),
            ("kWs185I2cSda", "kPeripheralControlSda"),
            ("kWs185I2cScl", "kPeripheralControlScl"),
            ("kWs185I2cClockHz", "kPeripheralControlClockHz"),
            ("kWs185TouchAddress", "kPeripheralControlTouchControllerAddress"),
            ("kWs185IoExpanderAddress", "kPeripheralControlIoExpanderAddress"),
            ("kWs185RtcAddress", "kPeripheralControlRtcAddress"),
            ("kWs185Es7210Address", "kPeripheralControlMicrophoneCodecAddress"),
            ("kWs185Es8311Address", "kPeripheralControlSpeakerCodecAddress"),
            ("kWs185AudioPort", "kAudioPort"),
            ("kWs185AudioMclk", "kAudioMclk"),
            ("kWs185AudioBclk", "kAudioBclk"),
            ("kWs185AudioLrclk", "kAudioLrclk"),
            ("kWs185AudioDin", "kAudioDin"),
            ("kWs185AudioDout", "kAudioDout"),
            ("kWs185DisplayClk", "kDisplayClk"),
            ("kWs185DisplayData0", "kDisplayData0"),
            ("kWs185DisplayData1", "kDisplayData1"),
            ("kWs185DisplayData2", "kDisplayData2"),
            ("kWs185DisplayData3", "kDisplayData3"),
            ("kWs185DisplayCs", "kDisplayCs"),
            ("kWs185DisplayTe", "kDisplayTe"),
            ("kWs185DisplayBacklight", "kDisplayBacklight"),
            ("kWs185TouchInterrupt", "kTouchInterrupt"),
            ("kWs185PaCtrl", "kSpeakerPa"),
            ("kWs185BatteryAdc", "kBatteryAdc"),
            ("kWs185SdmmcClk", "kSdmmcClk"),
            ("kWs185SdmmcCmd", "kSdmmcCmd"),
            ("kWs185SdmmcD0", "kSdmmcD0"),
        ]
    for alias, target in aliases:
        lines.append(f"constexpr int {alias} = {target};")

    lines.extend(
        [
            "",
            "}  // namespace hexe::board::pins",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a CMake board adapter fragment from a Hexe board profile.")
    parser.add_argument("--profile-root", type=Path, default=Path("firmware/boards"))
    parser.add_argument("--board-profile", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--header-output", type=Path)
    args = parser.parse_args()

    profile_path = args.profile_root / args.board_profile / "board.yaml"
    if not profile_path.exists():
        print(f"Unsupported HEXE_BOARD_PROFILE: {args.board_profile}", file=sys.stderr)
        print(f"Missing board profile file: {profile_path}", file=sys.stderr)
        return 1

    try:
        profile = load_profile(profile_path)
        validate_profile(profile, profile_path)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(render_cmake(profile, profile_path), encoding="utf-8")
        if args.header_output is not None:
            args.header_output.parent.mkdir(parents=True, exist_ok=True)
            args.header_output.write_text(render_pin_header(profile, profile_path), encoding="utf-8")
    except (OSError, ValidationError) as exc:
        print(f"Failed to generate board profile config: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
