#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="${IDF_TARGET:-esp32s3}"
EXPORT_AFTER_BUILD="${EXPORT_AFTER_BUILD:-1}"
COMMAND="${1:-build}"
CONVERTER_PYTHON="python3"
RUNTIME_FIRMWARE_DIR="${RUNTIME_FIRMWARE_DIR:-${ROOT_DIR}/../runtime/firmware}"
OTA_API_BASE="${OTA_API_BASE:-http://127.0.0.1:${API_PORT:-9004}}"
COMMON_EXPORT_DIR="${COMMON_EXPORT_DIR:-${ROOT_DIR}/export}"
BOARD_PROFILE_ROOT="${BOARD_PROFILE_ROOT:-${ROOT_DIR}/boards}"
PARTITION_ROOT="${PARTITION_ROOT:-${ROOT_DIR}/partitions}"
PARTITION_VALIDATOR="${ROOT_DIR}/tools/validate_partition_schema.py"
FIRMWARE_APP="${HEXE_FIRMWARE_APP:-endpoint}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [build|push]

Commands:
  build  Build firmware and refresh runtime/export artifacts. Builds both profiles by default.
  push   Build one firmware profile, refresh artifacts, then push OTA to the endpoint.

Environment:
  HEXE_BOARD_PROFILE  Firmware board profile: esp_box_3, ha_voice_pe, or all. Default: all for build, esp_box_3 for push.
  HEXE_FIRMWARE_APP    Firmware app to build. Default: endpoint.
  BUILD_DIR     ESP-IDF build directory. Defaults to build or build-ha-voice-pe by profile.
  EXPORT_DIR    Firmware export directory. Defaults to export or export-ha-voice-pe by profile.
  COMMON_EXPORT_DIR  Folder that receives profile-named binaries for all builds. Default: firmware/export.
  OTA_API_BASE   Backend API base URL for push mode. Default: ${OTA_API_BASE}
  ENDPOINT_ID    Endpoint id for push mode. Default: endpoint.id from config YAML.
  FIRMWARE_PROJECT_VERSION  Explicit ESP-IDF project version. Default: zYYYYMMDDHHMMSS-<git-sha>.
  ALLOW_DIRTY_FIRMWARE_BUILD=1  Allow building from tracked uncommitted changes. Export still rejects dirty versions.
EOF
}

yaml_value() {
  local section="$1"
  local key="$2"
  local config_path="${ROOT_DIR}/config/endpoint.yaml"
  if [[ ! -f "${config_path}" ]]; then
    config_path="${ROOT_DIR}/config/endpoint.example.yaml"
  fi
  awk -v section="${section}" -v key="${key}" '
    /^[^[:space:]#][^:]*:/ {
      current=$1
      sub(":", "", current)
    }
    current == section && $1 == key ":" {
      $1=""
      sub(/^[[:space:]]*/, "", $0)
      gsub(/^["'\'']|["'\'']$/, "", $0)
      print $0
      exit
    }
  ' "${config_path}"
}

json_value() {
  local key="$1"
  local manifest_path="$2"
  "${CONVERTER_PYTHON}" - "$key" "${manifest_path}" <<'PY'
import json
import sys

key = sys.argv[1]
path = sys.argv[2]
with open(path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)
value = payload.get(key)
print("" if value is None else value)
PY
}

board_profile_value() {
  local profile="$1"
  local dotted_key="$2"
  "${CONVERTER_PYTHON}" - "${BOARD_PROFILE_ROOT}" "${profile}" "${dotted_key}" <<'PY'
import sys
from pathlib import Path

root = Path(sys.argv[1])
profile = sys.argv[2]
dotted_key = sys.argv[3]
sys.path.insert(0, str(root.parent / "tools"))
from validate_board_profiles import load_profile, validate_profile  # noqa: E402

path = root / profile / "board.yaml"
payload = load_profile(path)
validate_profile(payload, path)
value = payload
for key in dotted_key.split("."):
    value = value[key]
if isinstance(value, bool):
    print("true" if value else "false")
elif value is None:
    print("")
else:
    print(value)
PY
}

partition_csv_for_schema() {
  case "$1" in
    s3-8m-v1) echo "partitions/s3_8m_v1.csv" ;;
    s3-16m-v1) echo "partitions/s3_16m_v1.csv" ;;
    p4-32m-v1) echo "partitions/p4_32m_v1.csv" ;;
    *)
      echo "Unsupported partition schema: $1" >&2
      exit 1
      ;;
  esac
}

profile_sdkconfig_path() {
  echo "$(profile_build_dir "$1")/sdkconfig"
}

profile_sdkconfig_defaults_path() {
  echo "$(profile_build_dir "$1")/sdkconfig.defaults.generated"
}

write_profile_sdkconfig_defaults() {
  local profile="$1"
  local schema
  local partition_csv
  local output
  schema="$(board_profile_value "${profile}" build.partition_schema)"
  partition_csv="$(partition_csv_for_schema "${schema}")"
  output="$(profile_sdkconfig_defaults_path "${profile}")"

  mkdir -p "$(dirname "${output}")"
  cat > "${output}" <<EOF
# Generated by firmware/build.sh for ${profile}.
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="${partition_csv}"
EOF
}

buildable_profiles() {
  "${CONVERTER_PYTHON}" - "${BOARD_PROFILE_ROOT}" <<'PY'
import sys
from pathlib import Path

root = Path(sys.argv[1])
sys.path.insert(0, str(root.parent / "tools"))
from validate_board_profiles import discover_profiles, load_profile, validate_profile  # noqa: E402

profiles = []
for path in discover_profiles(root):
    payload = load_profile(path)
    validate_profile(payload, path)
    if payload["adapters"]["buildable"]:
        profiles.append(payload["board_profile"])
print(" ".join(profiles))
PY
}

runtime_component_for_app() {
  case "$1" in
    endpoint) echo "endpoint_runtime" ;;
    recovery) echo "recovery_runtime" ;;
    *)
      echo "Unsupported HEXE_FIRMWARE_APP: $1" >&2
      exit 1
      ;;
  esac
}

firmware_api_version_for_app() {
  case "$1" in
    endpoint) echo "hexe-firmware-main-api-v1" ;;
    recovery) echo "hexe-recovery-api-v1" ;;
    *)
      echo "Unsupported HEXE_FIRMWARE_APP: $1" >&2
      exit 1
      ;;
  esac
}

profile_build_dir() {
  if [[ "${FIRMWARE_APP}" == "recovery" ]]; then
    echo "${BUILD_DIR:-${ROOT_DIR}/build-recovery-$1}"
    return
  fi
  case "$1" in
    esp_box_3) echo "${BUILD_DIR:-${ROOT_DIR}/build}" ;;
    ha_voice_pe) echo "${BUILD_DIR:-${ROOT_DIR}/build-ha-voice-pe}" ;;
    *) echo "${BUILD_DIR:-${ROOT_DIR}/build-$1}" ;;
  esac
}

profile_export_dir() {
  if [[ "${FIRMWARE_APP}" == "recovery" ]]; then
    echo "${EXPORT_DIR:-${ROOT_DIR}/export-recovery-$1}"
    return
  fi
  case "$1" in
    esp_box_3) echo "${EXPORT_DIR:-${ROOT_DIR}/export}" ;;
    ha_voice_pe) echo "${EXPORT_DIR:-${ROOT_DIR}/export-ha-voice-pe}" ;;
    *) echo "${EXPORT_DIR:-${ROOT_DIR}/export-$1}" ;;
  esac
}

profile_app_filename() {
  if [[ "${FIRMWARE_APP}" == "endpoint" ]]; then
    echo "hexe_firmware_${1}.bin"
  else
    echo "hexe_${FIRMWARE_APP}_${1}.bin"
  fi
}

profile_manifest_path() {
  echo "${RUNTIME_FIRMWARE_DIR}/manifest-${1}.json"
}

git_short_sha() {
  git -C "${ROOT_DIR}/.." rev-parse --short HEAD 2>/dev/null || echo "nogit"
}

git_has_tracked_changes() {
  ! git -C "${ROOT_DIR}/.." diff-index --quiet HEAD -- 2>/dev/null
}

ota_safe_project_version() {
  if [[ -n "${FIRMWARE_PROJECT_VERSION:-}" ]]; then
    echo "${FIRMWARE_PROJECT_VERSION}"
    return
  fi
  printf 'z%s-%s\n' "$(date -u +"%Y%m%d%H%M%S")" "$(git_short_sha)"
}

require_clean_firmware_source() {
  if [[ "${ALLOW_DIRTY_FIRMWARE_BUILD:-0}" == "1" ]]; then
    return
  fi
  if git_has_tracked_changes; then
    echo "Refusing to build OTA firmware from tracked uncommitted changes." >&2
    echo "Commit or stash changes first, or set ALLOW_DIRTY_FIRMWARE_BUILD=1 for a local non-release build." >&2
    exit 1
  fi
}

validate_profile() {
  local profile="$1"
  if [[ ! -f "${BOARD_PROFILE_ROOT}/${profile}/board.yaml" ]]; then
    echo "Unsupported HEXE_BOARD_PROFILE: ${profile}" >&2
    exit 1
  fi
  if [[ "${FIRMWARE_APP}" == "endpoint" && "$(board_profile_value "${profile}" adapters.buildable)" != "true" ]]; then
    echo "Board profile ${profile} is defined but its firmware adapters are not buildable yet." >&2
    exit 1
  fi
  if [[ "${FIRMWARE_APP}" == "recovery" ]]; then
    if [[ "$(board_profile_value "${profile}" build.recovery_app)" != "true" ]]; then
      echo "Board profile ${profile} does not declare recovery app support." >&2
      exit 1
    fi
    if [[ "$(board_profile_value "${profile}" build.idf_target)" != "esp32s3" ]]; then
      echo "Recovery skeleton currently supports only esp32s3 profiles." >&2
      exit 1
    fi
  fi
}

build_profile() {
  local profile="$1"
  validate_profile "${profile}"

  local build_dir
  local export_dir
  local profile_app
  local idf_target
  local sdkconfig_path
  local sdkconfig_defaults_path
  build_dir="$(profile_build_dir "${profile}")"
  export_dir="$(profile_export_dir "${profile}")"
  profile_app="$(profile_app_filename "${profile}")"
  idf_target="$(board_profile_value "${profile}" build.idf_target)"
  write_profile_sdkconfig_defaults "${profile}"
  sdkconfig_path="$(profile_sdkconfig_path "${profile}")"
  sdkconfig_defaults_path="$(profile_sdkconfig_defaults_path "${profile}")"

  echo "Building firmware profile ${profile} version ${PROJECT_VERSION}"
  local idf_env=("IDF_TARGET=${idf_target}")
  if [[ "${FIRMWARE_APP}" == "recovery" && -z "${IDF_COMPONENT_MANAGER:-}" ]]; then
    idf_env+=("IDF_COMPONENT_MANAGER=0")
  fi
  env "${idf_env[@]}" idf.py \
    -B "${build_dir}" \
    -D "SDKCONFIG=${sdkconfig_path}" \
    -D "SDKCONFIG_DEFAULTS=${ROOT_DIR}/sdkconfig.defaults;${sdkconfig_defaults_path}" \
    -D "HEXE_FIRMWARE_APP=${FIRMWARE_APP}" \
    -D "HEXE_BOARD_PROFILE=${profile}" \
    -D "PROJECT_VER=${PROJECT_VERSION}" \
    build

  "${CONVERTER_PYTHON}" "${PARTITION_VALIDATOR}" \
    --profile-root "${BOARD_PROFILE_ROOT}" \
    --partition-root "${PARTITION_ROOT}" \
    --board-profile "${profile}" \
    --app-binary "${build_dir}/hexe_firmware.bin"

  if [[ "${EXPORT_AFTER_BUILD}" == "1" ]]; then
    HEXE_BOARD_PROFILE="${profile}" \
      BUILD_DIR="${build_dir}" \
      EXPORT_DIR="${export_dir}" \
      COMMON_EXPORT_DIR="${COMMON_EXPORT_DIR}" \
      UPDATE_RUNTIME_FIRMWARE=1 \
      PROFILE_APP_FILENAME="${profile_app}" \
      PROFILE_MANIFEST_FILENAME="manifest-${profile}.json" \
      FIRMWARE_APPLICATION_TYPE="${FIRMWARE_APP}" \
      FIRMWARE_API_VERSION="$(firmware_api_version_for_app "${FIRMWARE_APP}")" \
      GENERATED_COMPONENT_NAME="$(runtime_component_for_app "${FIRMWARE_APP}")" \
      "${ROOT_DIR}/export-artifacts.sh"
  fi
}

push_ota() {
  local profile="$1"
  if [[ "${FIRMWARE_APP}" != "endpoint" ]]; then
    echo "push mode supports only HEXE_FIRMWARE_APP=endpoint." >&2
    exit 1
  fi
  local endpoint_id="${ENDPOINT_ID:-$(yaml_value endpoint id)}"
  local filename
  local manifest_path
  local version
  filename="$(profile_app_filename "${profile}")"
  manifest_path="$(profile_manifest_path "${profile}")"
  version="$(json_value version "${manifest_path}")"

  if [[ -z "${endpoint_id}" ]]; then
    echo "Missing ENDPOINT_ID and could not read endpoint.id from firmware config." >&2
    exit 1
  fi
  if [[ ! -f "${RUNTIME_FIRMWARE_DIR}/${filename}" ]]; then
    echo "Missing ${RUNTIME_FIRMWARE_DIR}/${filename}; build did not produce a runtime firmware binary." >&2
    exit 1
  fi

  echo "Pushing ${profile} firmware OTA to ${endpoint_id} via ${OTA_API_BASE}"
  curl -fsS -X POST "${OTA_API_BASE%/}/api/firmware/ota/push" \
    -H "Content-Type: application/json" \
    -d "{\"endpoint_id\":\"${endpoint_id}\",\"filename\":\"${filename}\",\"version\":\"${version}\"}"
  echo
}

case "${COMMAND}" in
  build|push)
    ;;
  -h|--help|help)
    usage
    exit 0
    ;;
  *)
    echo "Unknown command: ${COMMAND}" >&2
    usage >&2
    exit 1
    ;;
esac

USER_HOME="${HOME:-$(getent passwd "$(id -u)" | cut -d: -f6 2>/dev/null || true)}"
USER_HOME="${USER_HOME:-$ROOT_DIR}"

if [[ -z "${IDF_PATH:-}" ]]; then
  if [[ -f "${USER_HOME}/esp-idf/export.sh" ]]; then
    # shellcheck disable=SC1090
    . "${USER_HOME}/esp-idf/export.sh"
  else
    echo "ESP-IDF environment is not loaded and ${USER_HOME}/esp-idf/export.sh was not found." >&2
    echo "Run '. ~/esp-idf/export.sh' first, or install ESP-IDF under ~/esp-idf." >&2
    exit 1
  fi
fi

cd "${ROOT_DIR}"

require_clean_firmware_source
PROJECT_VERSION="$(ota_safe_project_version)"

requested_profile="${HEXE_BOARD_PROFILE:-}"
if [[ "${COMMAND}" == "push" && -z "${requested_profile}" ]]; then
  requested_profile="esp_box_3"
elif [[ -z "${requested_profile}" ]]; then
  requested_profile="all"
fi

if [[ "${requested_profile}" == "all" && (-n "${BUILD_DIR:-}" || -n "${EXPORT_DIR:-}") ]]; then
  echo "BUILD_DIR and EXPORT_DIR overrides require a single HEXE_BOARD_PROFILE." >&2
  exit 1
fi

case "${requested_profile}" in
  all)
    if [[ "${COMMAND}" == "push" ]]; then
      echo "push mode requires a single buildable HEXE_BOARD_PROFILE." >&2
      exit 1
    fi
    read -r -a profiles_to_build <<< "$(buildable_profiles)"
    if [[ "${#profiles_to_build[@]}" -eq 0 ]]; then
      echo "No buildable board profiles found in ${BOARD_PROFILE_ROOT}." >&2
      exit 1
    fi
    for profile in "${profiles_to_build[@]}"; do
      build_profile "${profile}"
    done
    ;;
  *)
    build_profile "${requested_profile}"
    ;;
esac

if [[ "${COMMAND}" == "push" ]]; then
  push_ota "${requested_profile}"
fi

echo "Firmware build complete."
